.\" Manpage for zps.
.TH ZPS "1" "January 2024" "zps" "User Commands"
.SH NAME
zps \- list/reap zombie processes
.SH SYNOPSIS
.B zps
[options]
.SH DESCRIPTION
zps lists the running processes with their stats and indicates/reaps the zombie processes.
.SH OPTIONS
.TP
.BR \-v ", " \-\-version
Show version information.
.TP
.BR \-h ", " \-\-help
Show the help text.
.TP
.BR \-a ", " \-\-all
List all user-space processes (not just zombies).
.TP
.BR \-r ", " \-\-reap
Reap zombie processes.
.TP
.BI \-s\  sig \fR,\ \fB\-\-signal= sig \fR,\ \fB\-\-signal \ sig
Use signal
.I sig
on zombie parents (default:
.BR SIGTERM ).
.TP
.BR \-p ", " \-\-prompt
Show prompt for selecting processes.
.TP
.BR \-q ", " \-\-quiet
Reap in quiet mode.
.TP
.BR \-n ", " \-\-no-color
Disable color output.
.SH BUGS
No known bugs.
Use "Issues" page for reporting bugs: <https://github.com/orhun/zps/issues/>
.SH AUTHOR
Written by Orhun Parmaksız <orhunparmaksiz@gmail.com>
.SH COPYRIGHT
Copyright © 2019-2024 Orhun Parmaksız
.P
GNU General Public License v3.0 only
